### PR TITLE
Add possibility to use custom environment variables

### PR DESCRIPTION
**Pull request by jnk0**
Thanks for creating this module!

Since you probably cannot map all environment variables as parameters, I have added a possibility to pass them in a separate parameter.

Please check my suggestion and let me know if you see a need for adjustments.

### CODE REVIEW

**Comment by knoppi** [comment]
Hi, thanks for your appreciation and your contribution.

Originally, I thought I would add more parameters to the class, but apparently I haven't done so, so your approach eventually is the better one. I have no objections to merging, just two questions:

1) Wouldn't a Hash fit better as a data type? To me this seems more natural and hiera would be cleaner in that case. With your choice, however, one could simply copy from an existing `.env` file. 

2) If you set a custom parameter for one of the already existing parameters, the custom parameter would overwrite the existing one since it comes later in the file, doesn't it? Is that the intention?

**Comment by jnk0** [comment]
Thanks for taking the time to review the PR and the feedback.

Regarding your questions:

1. Yes, I thought it might be better to copy the needed environment variable from `.env` file in the repository or the documentation. Using a hash in Hiera would mean to either live with a mix of parameters in upper or lower case letters or to implement a logic for a 1:1 conversation of lower case parameters to upper case environment variables. To take it further, wouldn't we then have to check the passed value of the parameter as well? 

We might highlight in the documentation, that the user is responsible to take over the variables correctly from the documentation or to adapt their values if necessary.

2. See my answer to 1. Wouldn't it mean to make it too complex if we even check given environment in custom_variables against there earlier appearance? I would suggest a pragmatic approach for the first implementation.

**Comment by jnk0** [comment]
In the future, one could work on converting all known environment variables into real parameters and only use custom_variables as a supplement if the developer of `docker-jitsi-meet` moves faster than you can.

**Comment by knoppi** [comment]
1) let's assume you had `Optional[Hash] $custom_variables`, your example hiera would be
```
jitsi::containerized_server::custom_variables:
  DISABLE_AUDIO_LEVELS: 0
  ENABLE_END_CONFERENCE: 0
```
In the template have
```
<% if @custom_variables -%>
  <% @custom_variables.each do |name, value| -%>
<%= name %>=<%= value %>
  <%- end -%>
<% end -%>
```
No further checks are required.

2) I'd propose to place the additional code in the template at the top, so the explicitly set parameters would overwrite your new custom parameters. That's why I asked if your intention was the other way round.

**Comment by jnk0** [comment]
1. Okay, I understood. If it's okay for you, to mix upper and lower case, it's okay for me too. I have adjusted the code.

2. But at the moment there are hard-coded environment variables in `.env` like `JVB_PORT=10000`. It wouldn't be possible to overwrite these settings.

**Comment by knoppi** [comment]
1. Yeah, I prefer that way.
2. You're right, didn't think about that.

**Comment by jnk0** [comment]
It seems that the reference between my branch [jnk0:develop](https://github.com/jnk0/puppet-jitsi/tree/develop) and this PR is gone. Could you kindly transfer the [changes](https://github.com/knoppi/puppet-jitsi/compare/develop...jnk0:puppet-jitsi:develop?expand=1) directly into the PR? Otherwise I will open an new PR with the corrected change.

**Comment by knoppi** [comment]
I will do so later.

**Comment by knoppi** [comment]
See #3

**Pull request closed without merging**
