### PR TITLE
Switch to Compose V2

### PR DESCRIPTION
**Pull request by jnk0**
Docker Compose V1 has stopped receiving updates [1] and should be replaced by V2. This PR aims to migrate to V2.

[1] https://docs.docker.com/compose/

### CODE REVIEW

**Comment by knoppi** [comment]
I think this is an improvement. Just a question: how would you ensure compose v2 is installed using puppet? Since it is a prerequisite now, we should tackle this.

Currently the inclusion of docker makes this class self consistent, but it will not provide compose v2.

**Comment by knoppi** [comment]
Do you have any update on this? (And I edited my last post. A 'not' was missing which spoilt the whole sentence.)

**Comment by jnk0** [comment]
It may not be necessary to force it. The Docker module now takes care of this ([PR#975](https://github.com/puppetlabs/puppetlabs-docker/pull/975)), and newer versions of Docker simply don't support Compose v1 anymore.

**Comment by knoppi** [comment]
Can you please update the metadata to contain docker >= 10.0.0 < 11.0.0?

There are other issues with the metadata that I will have a look at at another point.

**Comment by jnk0** [comment]
I have updated the dependency on the puppetlabs-docker module.

**Comment by knoppi** [comment]
Thanks for your contribution. I will finalize a new release soon and publish it on Puppet Forge.

**Comment by knoppi** [comment]
@jnk0 Your changes are available in version 2.0.0 of the module available on Puppet forge.

**Pull request merged**
